---
# Python interpreter — explícito para evitar warning de auto-discovery
ansible_python_interpreter: /usr/bin/python3

# Static site source
app_repo_url: https://github.com/dsalazarCazanhas/Static-Site-Server
app_repo_dest: /tmp/static-site-repo
app_repo_version: master
app_site_subdir: site

# Nginx
nginx_web_root: /var/www/html
nginx_server_name: "{{ ansible_host }}"

# Node.js app
node_app_repo_url: https://github.com/dsalazarCazanhas/Configuration-Management-Ansible
node_app_dir: /opt/hello-world
node_app_entry: app/server.js
node_app_name: hello-world
node_app_port: 3000
